Created Result page
HakinCodes/Malaria-Detection pull request #174
Opened 2020-09-23 13:59 UTC by rutujadhanawade

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/HakinCodes/Malaria-Detection/blob/master/CONTRIBUTING.md)?

YES

### Description

 Created the Results Page using HTML, CSS, Bootstrap, JQuery. By using this [UI Design](https://github.com/HakinCodes/Malaria-Detection/blob/master/design/webpage_designs/result_page.png) .

### Checklist

- [x] I've read the contribution guidelines.
- [x] This PR mets all the requirements like Clean Code, proper README and Documentation

### Related Issues or Pull Requests

Fixes: #125 

### Screenshots (if any)

![op1](https://user-images.githubusercontent.com/53823042/94022570-dc58fb80-fdd2-11ea-8b7e-746b4c19cc24.png)

2020-09-24 05:11 UTC, kahanikaar commented
The Frontend looks good, do just check once the alignment responsiveness of the buttons.

2020-09-24 05:13 UTC, kahanikaar reviewed
The Frontend looks good, do just check once the alignment responsiveness of the buttons.

2020-09-24 15:11 UTC, rutujadhanawade commented
Hi @kahanikaar buttons are responsive. But the images are not actually responsive. I used the max width property but still it is not showing much difference. Will you give me suggestion to make them responsive.

2020-09-24 18:03 UTC, kahanikaar commented
> @kahanikaar buttons are responsive.

A suggestion, try using bootstrap containers, will be better in making it responsive, and also try using relative values for css fields.

2020-09-26 09:34 UTC, rutujadhanawade commented
@kahanikaar Please review this. I have made all the necessary changes.

2020-09-28 03:11 UTC, kahanikaar requested changes
The rest frontend looks good. Aligns with the requirement.

2020-09-28 03:11 UTC, kahanikaar commented on templates/result.html
> +    <button  type="button" class="imageBtn"><b>Maleria Cell</b></button>
Check the typo of malaria here

2020-09-28 04:15 UTC, rutujadhanawade commented
Fixed typo @kahanikaar

2020-09-28 09:03 UTC, kahanikaar approved these changes
Looks good to me. Approved from my side. Do review @HarshCasper @sarthakkundra @BALaka-18

2020-09-28 14:08 UTC, sarthakkundra approved these changes
Looks good! 👍

2020-09-28 14:13 UTC, BALaka-18 approved these changes
Looks good to me.

2020-09-28 14:54 UTC, sarthakkundra commented
@BALaka-18 I have merged the restyled PR you can add the respective points.

2020-09-28 14:54 UTC, closed without merging